name: deploying
on: [push,workflow_dispatch]
jobs:
    deployment:
        runs-on: windows-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: install dependencies
              run: npm ci
            - name: linting test
              run: npoom run lint
            - name: testing code
              run: npm run test
            - name: building code
              run: npm run build
            - name: deploying code
              run: echo "deploying...."
