name: deploying
on: [push,workflow_dispatch]
jobs:
    lintingt:
        runs-on: windows-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: install dependencies
              run: npm ci
            - name: linting test
              run: npm run lint
    testing:
        runs-on: windows-latest
        needs:  lintingt
        steps:
           - name: checking code
             uses: actions/checkout@v3
           - name: installing dependencies
             run: npm ci
           - name: testing code
             run: npm run test
    deploying:
        runs-on: windows-latest
        needs: [lintingt,testing]
        steps:
            - name: checking code
              uses: actions/checkout@v3
            - name: installing dependencies
              run: npm ci
            - name: building code
              run: npm run build 
            - name: deploying code
              run:  echo " deploying code"